# Generated by Django 5.0.4 on 2024-05-03 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zhk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('name_developer', models.CharField(max_length=100, verbose_name='Название застройщика')),
                ('get_id', models.CharField(max_length=3, verbose_name='ID проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('zhk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zhk', verbose_name='Подключение')),
            ],
        ),
    ]
